### ISSUE TITLE
Create doc about principal colors on the App

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#1]
Based on Mara's response about the main color she uses on her designs. Create doc in Google Drive share folder for this project with the hexadecimal colors. Indicate what are more used.

**Comment by Inatedy** [comment]
Should we  create a folder named "design" in mexico trasciende

**Comment by MartinMelo97** [comment]
Yes pls

**Comment by MartinMelo97** [comment]
Upload the color for the our own color pallete pls.

**Comment by MartinMelo97** [comment]
Upload a doc with the four color of our color palleter into Docs folder pls.

**Comment by MartinMelo97** [comment]
I need the hexadecimal color of each color, pls.
