### ISSUE TITLE
Speakers Desktop UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#10]
Based on Speaker Mobile version mockup. Extend to a Desktop Version.

**Comment by Inatedy** [comment]
![Navbar desktop mockup #6 #9 #10 #13 -2](https://user-images.githubusercontent.com/46948948/63045398-e2716e80-be95-11e9-9396-333a611cb100.png)
![Navbar desktop mockup #6 #9 #10 #13 -3](https://user-images.githubusercontent.com/46948948/63045399-e2716e80-be95-11e9-811e-4a590009d6fc.png)
![Navbar desktop mockup #6 #9 #10 #13](https://user-images.githubusercontent.com/46948948/63045400-e2716e80-be95-11e9-9d2b-6e439d084e34.png)

**Comment by MartinMelo97** [comment]
That are great! Upload it to Drive
