### ISSUE TITLE
Team Organizer Mobile UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#11]
Create a UI Mockup for the Team Organizer of the Event.

**Info about each organizer**
- Name
- Career
- Role

You could user cards, list views, any do you want to try its ok. Feel with the freedom to propose anything

**Comment by Emily-Garcia** [comment]
![MOBILE ORGANIZER TEAM](https://user-images.githubusercontent.com/52437193/62890778-c4770300-bd09-11e9-8b7b-064b8ddbd1c2.png)
