### ISSUE TITLE
Date / Duration / Place of the event Mobile UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#12]
I think that this component it's so important and we skipped in the morning. We need to show to the user when will be the event, the schedule of the ssame and where it going to happen. This mockup **have** be placed between About Us and Speakers.

**Extras**
This component of the landing page doesn't be a full height. But we need to show this information in a very pretty and so highlighted way. This need to capture the attention of the users.

**Comment by Emily-Garcia** [comment]
![MOBILE DATE – 2](https://user-images.githubusercontent.com/52437193/62816703-e5184080-baf0-11e9-9375-81c0153d1187.png)

**Comment by Emily-Garcia** [comment]
![MOBILE DATE – 2](https://user-images.githubusercontent.com/52437193/62823860-d31fb780-bb5b-11e9-9115-8faa38f1d4f9.png)

**Comment by MartinMelo97** [comment]
Missing *acento* on Día.
