### ISSUE TITLE
Sponsors Mobile Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#14]
Design a sponsors component, we need to show ALL the sponsor who contribute to this event.

**Info of each sponsor**
- Name
- Logo or Image
- Facebook / Twitter / Intagram Icon who redirect to its social media

**Comment by Inatedy** [comment]
![Sponsors Mobile Mockup #14 NORMAL](https://user-images.githubusercontent.com/46948948/62829257-6b9b5380-bbbf-11e9-9972-6f83774fb8d8.png)
![Sponsors Mobile Mockup #14 ONCLIC](https://user-images.githubusercontent.com/46948948/62829259-6b9b5380-bbbf-11e9-9b5c-bec6df2bd515.png)

**Comment by MartinMelo97** [comment]
The second image is when users click on this sponsor? I think that could be better 2 sponsors per row.

**Comment by Inatedy** [comment]
sip,
![Sponsors Mobile Mockup #14 NORMAL – 3](https://user-images.githubusercontent.com/46948948/62884264-b0c4a000-bcfb-11e9-8cbe-71dc2e25183e.png)
![Sponsors Mobile Mockup #14 NORMAL – 2](https://user-images.githubusercontent.com/46948948/62884265-b15d3680-bcfb-11e9-861f-fcf213ad6b1a.png)

**Comment by Inatedy** [comment]
sip,
![Sponsors Mobile Mockup #14 NORMAL – 3](https://user-images.githubusercontent.com/46948948/62884573-858e8080-bcfc-11e9-971f-5c784b6b63ba.png)
![Sponsors Mobile Mockup #14 NORMAL – 2](https://user-images.githubusercontent.com/46948948/62884574-858e8080-bcfc-11e9-947a-4c5b6e8b6bb4.png)

**Comment by MartinMelo97** [comment]
Yes, two in a row. Upload it to Drive
