### ISSUE TITLE
Team organizer Desktop UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#15]
Based on *Team Organizer Mobile Version* extends to a Desktop Version

**Comment by Inatedy** [comment]
![Team organizer Desktop UI Mockup #15 #16](https://user-images.githubusercontent.com/46948948/63045547-34b28f80-be96-11e9-8ea4-e247d4688249.png)

**Comment by MartinMelo97** [comment]
Ok, this looks great. Upload it to Drive
