### ISSUE TITLE
Sponsors Desktop UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#16]
Based on *Sponsors UI Mobile Version* extends to a Desktop Version

**Comment by Inatedy** [comment]
![Team organizer Desktop UI Mockup #15 #16 -2](https://user-images.githubusercontent.com/46948948/63045605-590e6c00-be96-11e9-91e5-d336d68de26c.png)
![Team organizer Desktop UI Mockup #15 #16](https://user-images.githubusercontent.com/46948948/63045606-590e6c00-be96-11e9-8d8b-95f48edd1e8b.png)

**Comment by MartinMelo97** [comment]
Ok, it's great, upload it to Drive.
