### ISSUE TITLE
Contact Mobile UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#17]
In the last section of the landing page, we need to handle the user to send a form for any comment or doubt it could have. So, we need to design a Contact Form

**Inputs**
Name (required)
Phone
Email (required)
Body (required)

- Button with a "Enviar" label to handle the send of the info.

**Extras**
Before the form with its inputs, put a label as "¿Tienes alguna duda o comentario? Estamos para escucharte, por favor, comunícate con nosotros con el siguiente formulario".

**Comment by Inatedy** [comment]
![Contact Mobile UI Mockup #17 -1](https://user-images.githubusercontent.com/46948948/63033403-2ad06280-be7d-11e9-8a85-fd8934721a08.png)
![Contact Mobile UI Mockup #17 -3](https://user-images.githubusercontent.com/46948948/63033404-2ad06280-be7d-11e9-8c31-6ab37667dccb.png)
![Contact Mobile UI Mockup #17 -5](https://user-images.githubusercontent.com/46948948/63033405-2b68f900-be7d-11e9-809d-fb8e722a3b54.png)
![Contact Mobile UI Mockup #17 -4](https://user-images.githubusercontent.com/46948948/63033408-2b68f900-be7d-11e9-9afa-204bf960d902.png)
![Contact Mobile UI Mockup #17 -2](https://user-images.githubusercontent.com/46948948/63033411-2c018f80-be7d-11e9-83ec-9a72d8dae229.png)

**Comment by MartinMelo97** [comment]
https://user-images.githubusercontent.com/46948948/63033405-2b68f900-be7d-11e9-809d-fb8e722a3b54.png This pls
