### ISSUE TITLE
Contact Desktop UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#18]
Based on *Contact Mobile Version*, extends to a Desktop version.

**Comment by Inatedy** [comment]
![Contact Desktop UI Mockup #18](https://user-images.githubusercontent.com/46948948/63045754-a1c62500-be96-11e9-92a5-42a50c9d7a41.png)
![Contact Desktop UI Mockup #18 on write](https://user-images.githubusercontent.com/46948948/63045755-a1c62500-be96-11e9-8b83-d499e2627513.png)

**Comment by MartinMelo97** [comment]
Yes, approved, only let 1 image about the contact pls (now are 2 images for slider and 2 for contact). Upload to Drive, create a new folder called "Desktop" and inside this mockups

**Comment by Inatedy** [comment]
es que el segundo tiene sobra porque esta escribiendo en el nombre
