### ISSUE TITLE
Slider with images and Countdown Mobile UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#19]
As we talked in the morning. The first content that the user will see it will be a slider with a very big images which cover the full screen. Below that slider and in a pretty, we're going to show a Countdown with the days, hours, minutes and second for the event.

**Comment by Emily-Garcia** [comment]
![MOBILE SLIDERRRR – 1](https://user-images.githubusercontent.com/52437193/62989545-11dc9880-be0e-11e9-88f2-6b3db1d974e6.png)
