### ISSUE TITLE
Slider with images and countdown Desktop UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#20]
Based on mobile version, extends to Desktop version

**Comment by Inatedy** [comment]
![Team organizer Desktop UI Mockup #15 #16](https://user-images.githubusercontent.com/46948948/63045860-dc2fc200-be96-11e9-9d60-2de31711eb32.png)

**Comment by MartinMelo97** [comment]
Upload it to Drive.
