### ISSUE TITLE
Navbar Mobile UI

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#4]
Upload the navbar mockup UI made on the morning (image) here as a comment and in Drive mockup folder.

**Comment by MartinMelo97** [comment]
Attach image of image pls.

**Comment by Inatedy** [comment]
![navbar](https://user-images.githubusercontent.com/46948948/62826818-4808e680-bb88-11e9-8a53-aaa8043b764e.png)
this?
