### ISSUE TITLE
Sidebar Mobile UI Mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#5]
Upload the mockup made in the morning about sidebar mobile (image). Upload as a comment here and in Drive folder.

**Comment by MartinMelo97** [comment]
Attach an image for the mockup pls.

**Comment by Inatedy** [comment]
![iPhone X-XS – 4](https://user-images.githubusercontent.com/46948948/62826826-5f47d400-bb88-11e9-9fbf-0d63201fd31d.png)
