### ISSUE TITLE
Navbar desktop mockup

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#6]
Design a navbar for desktop. in this navbar we must have the mobile sidebar links into the navbar, because here we have more space. When it's done. Upload the image here as comment and into Drive folder. Keep design patterns about #4. Remember that we're using "mobile first design pattern" so this navbar for desktop it's only "extend" the mobile navbar.

**Comment by Inatedy** [comment]
![Navbar desktop mockup #6 #9 #10 #13](https://user-images.githubusercontent.com/46948948/63045151-6414cc80-be95-11e9-8f9d-cdd557fd305f.png)
