### ISSUE TITLE
About Us Mobile UI

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#7]
Create UI for About Us Component on Mobile Version. In this components, we need to show the summary about the event. (You can copy and paste the info in the "Resumen del Evento" PDF on Drive.

Take care about letter sizing, text alignment line height and padding an margin

**Comment by Emily-Garcia** [comment]
![MOBILE ABOUT US](https://user-images.githubusercontent.com/52437193/62809123-af0e9880-babf-11e9-8052-0977b9178533.png)
