### ISSUE TITLE
Speakers UI Mockup Mobile

### ISSUE THREAD

**Issue by MartinMelo97** [ActoSoft/MexicoTrasciende-Frontend#8]
Design the speakers UI Mockup as we talked in the morning. As this part of the landing page will has animation, i recommend the following.

- Mockup with all the speakers
- Mockup with a speaker is focused (The focus will be applied when the user scroll and this speaker is in the middle of the page)
- Mockup with all the speaker info (When a user click on someone speaker, we will resize it card to a fullwidth and with a little speech about this speaker).

Any doubt please let me know.

**Comment by Inatedy** [comment]
![Speakers UI Mockup Mobile #8 normal](https://user-images.githubusercontent.com/46948948/62825950-96fb4f80-bb79-11e9-807b-2d209c66bd56.png)
![Speakers UI Mockup Mobile #8  focus](https://user-images.githubusercontent.com/46948948/62825951-9793e600-bb79-11e9-83cd-f648c76dd717.png)
![Speakers UI Mockup Mobile #8  on clic](https://user-images.githubusercontent.com/46948948/62825953-982c7c80-bb79-11e9-87fb-2c4dceb29b48.png)

**Comment by MartinMelo97** [comment]
In "On Click" mockup could try make the card of Paola cover everything? 100% width. And also use other social media icons. Edith solid color instead outlind

**Comment by MartinMelo97** [comment]
And make tue text of DESC a little more bigger

**Comment by Inatedy** [comment]
![Speakers UI Mockup Mobile #8 normal](https://user-images.githubusercontent.com/46948948/62826104-a24f7a80-bb7b-11e9-9ef7-f0e1a436cd8a.png)
![Speakers UI Mockup Mobile #8  focus](https://user-images.githubusercontent.com/46948948/62826105-a24f7a80-bb7b-11e9-9b76-1eae1f4e62ab.png)
![Speakers UI Mockup Mobile #8  on clic](https://user-images.githubusercontent.com/46948948/62826106-a2e81100-bb7b-11e9-922b-52b8e3cbc59f.png)

**Comment by MartinMelo97** [comment]
Ok, lets change the instagram icon for the new logo https://cdn4.iconfinder.com/data/icons/social-messaging-ui-color-shapes-2-free/128/social-instagram-new-circle-512.png
And put a bigger text pls to see how this is look

**Comment by Inatedy** [comment]
![Speakers UI Mockup Mobile #8  on clic](https://user-images.githubusercontent.com/46948948/62826299-d11b2000-bb7e-11e9-8fca-6c009ae53416.png)
![Speakers UI Mockup Mobile #8 normal](https://user-images.githubusercontent.com/46948948/62826300-d11b2000-bb7e-11e9-8c7e-d4652c61f062.png)
![Speakers UI Mockup Mobile #8  focus](https://user-images.githubusercontent.com/46948948/62826301-d11b2000-bb7e-11e9-8a90-3899d6875825.png)

**Comment by MartinMelo97** [comment]
Great. We'll approve this. Upload it to Drive pls.
